
insert into Customer (id, first_name, last_name, email, role, billing_id) values (1, 'Madonna', 'Joncic', 'mjoncic0@sourceforge.net', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (2, 'Tabbatha', 'Kardos', 'tkardos1@ca.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (3, 'Nora', 'Klainman', 'nklainman2@ebay.co.uk', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (4, 'Jackie', 'McVanamy', 'jmcvanamy3@businesswire.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (5, 'Manda', 'Howells', 'mhowells4@vimeo.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (6, 'Sianna', 'Rowaszkiewicz', 'srowaszkiewicz5@github.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (7, 'Jamima', 'Oulett', 'joulett6@opera.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (8, 'Euphemia', 'Merrien', 'emerrien7@sun.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (9, 'Torrin', 'Simyson', 'tsimyson8@npr.org', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (10, 'Bab', 'Joppich', 'bjoppich9@gravatar.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (11, 'Rudd', 'Gagan', 'rgagana@wsj.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (12, 'Ashley', 'Glasard', 'aglasardb@hugedomains.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (13, 'Audrey', 'Umfrey', 'aumfreyc@marriott.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (14, 'Mellisa', 'Farquhar', 'mfarquhard@typepad.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (15, 'Brunhilde', 'Loan', 'bloane@php.net', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (16, 'Velma', 'Sapsforde', 'vsapsfordef@sciencedirect.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (17, 'Kendre', 'Bradbury', 'kbradburyg@dagondesign.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (18, 'Briggs', 'Riba', 'bribah@virginia.edu', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (19, 'Edmund', 'Grishmanov', 'egrishmanovi@addthis.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (20, 'Rozalie', 'Attac', 'rattacj@macromedia.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (21, 'Luella', 'Gierke', 'lgierkek@columbia.edu', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (22, 'Hillard', 'Lorentzen', 'hlorentzenl@state.gov', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (23, 'Flossie', 'Deluca', 'fdelucam@ca.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (24, 'Puff', 'Bouskill', 'pbouskilln@irs.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (25, 'Cicily', 'Dorking', 'cdorkingo@wufoo.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (26, 'Rozina', 'Lambertson', 'rlambertsonp@chicagotribune.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (27, 'Elsie', 'Vanyarkin', 'evanyarkinq@liveinternet.ru', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (28, 'Fulton', 'Leipelt', 'fleipeltr@desdev.cn', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (29, 'Holt', 'Faldoe', 'hfaldoes@wordpress.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (30, 'Ynez', 'Phillipson', 'yphillipsont@techcrunch.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (31, 'Edithe', 'Harcombe', 'eharcombeu@sohu.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (32, 'Tobe', 'Josefovic', 'tjosefovicv@miibeian.gov.cn', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (33, 'Estevan', 'McPolin', 'emcpolinw@w3.org', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (34, 'Devland', 'Sked', 'dskedx@rediff.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (35, 'Lynnette', 'Cadge', 'lcadgey@java.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (36, 'Sonny', 'Witheford', 'swithefordz@techcrunch.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (37, 'Cecile', 'Gergler', 'cgergler10@ebay.co.uk', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (38, 'Jacynth', 'Kiendl', 'jkiendl11@washingtonpost.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (39, 'Francis', 'Spivie', 'fspivie12@ycombinator.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (40, 'Sigismondo', 'Hanselmann', 'shanselmann13@apache.org', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (41, 'Nevin', 'Peever', 'npeever14@dailymotion.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (42, 'Shaina', 'Coslitt', 'scoslitt15@geocities.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (43, 'Zebadiah', 'Worsham', 'zworsham16@omniture.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (44, 'Abe', 'Beardall', 'abeardall17@fda.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (45, 'Wallie', 'Marsters', 'wmarsters18@sciencedaily.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (46, 'Shea', 'Meyrick', 'smeyrick19@jugem.jp', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (47, 'Lavena', 'Finkle', 'lfinkle1a@example.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (48, 'Marge', 'Heintzsch', 'mheintzsch1b@theguardian.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (49, 'Sophey', 'Walewski', 'swalewski1c@ibm.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (50, 'Englebert', 'Rossbrook', 'erossbrook1d@printfriendly.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (51, 'Courtenay', 'Garritley', 'cgarritley1e@wunderground.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (52, 'Jolie', 'Simonnin', 'jsimonnin1f@nih.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (53, 'Fletcher', 'Senescall', 'fsenescall1g@drupal.org', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (54, 'Ealasaid', 'Oulet', 'eoulet1h@edublogs.org', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (55, 'Jerry', 'Whapple', 'jwhapple1i@jimdo.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (56, 'Eugenio', 'Standage', 'estandage1j@archive.org', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (57, 'Del', 'Mabon', 'dmabon1k@list-manage.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (58, 'Modesta', 'Pollard', 'mpollard1l@wikimedia.org', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (59, 'Johannah', 'Cleve', 'jcleve1m@tmall.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (60, 'Dennet', 'Scuffham', 'dscuffham1n@google.pl', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (61, 'Tracee', 'Knibbs', 'tknibbs1o@cloudflare.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (62, 'Velvet', 'Allsupp', 'vallsupp1p@slideshare.net', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (63, 'Rollin', 'Champkins', 'rchampkins1q@flickr.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (64, 'Laurence', 'Fashion', 'lfashion1r@umich.edu', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (65, 'Bibi', 'Meran', 'bmeran1s@furl.net', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (66, 'Kaiser', 'Elloit', 'kelloit1t@deliciousdays.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (67, 'Sherlocke', 'Sommerland', 'ssommerland1u@t-online.de', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (68, 'Aarika', 'Airdrie', 'aairdrie1v@studiopress.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (69, 'Arin', 'Mault', 'amault1w@cnn.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (70, 'Daren', 'Welfare', 'dwelfare1x@furl.net', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (71, 'Glenda', 'Cleeves', 'gcleeves1y@fema.gov', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (72, 'Timi', 'Hutcheson', 'thutcheson1z@csmonitor.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (73, 'Kiri', 'Gout', 'kgout20@livejournal.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (74, 'Sean', 'Sire', 'ssire21@issuu.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (75, 'Stoddard', 'Matskiv', 'smatskiv22@sphinn.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (76, 'Tresa', 'Kohneke', 'tkohneke23@tuttocitta.it', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (77, 'Felicia', 'Magenny', 'fmagenny24@baidu.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (78, 'Christalle', 'Birkett', 'cbirkett25@naver.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (79, 'Hendrick', 'Evequot', 'hevequot26@gravatar.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (80, 'Janaya', 'Dickon', 'jdickon27@bizjournals.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (81, 'Darius', 'Larimer', 'dlarimer28@rakuten.co.jp', 'ADMIN', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (82, 'Theodor', 'Bullough', 'tbullough29@patch.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (83, 'Cortie', 'Benezet', 'cbenezet2a@house.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (84, 'Rhys', 'Berthomieu', 'rberthomieu2b@dion.ne.jp', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (85, 'Berry', 'Matzkaitis', 'bmatzkaitis2c@springer.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (86, 'Rebe', 'Camilio', 'rcamilio2d@zimbio.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (87, 'Murray', 'Carcass', 'mcarcass2e@cbslocal.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (88, 'Lorita', 'Rawet', 'lrawet2f@furl.net', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (89, 'Emmet', 'Alibone', 'ealibone2g@vistaprint.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (90, 'Griff', 'Ferrant', 'gferrant2h@cnn.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (91, 'Juan', 'Rottcher', 'jrottcher2i@earthlink.net', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (92, 'Shirl', 'Farraway', 'sfarraway2j@pcworld.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (93, 'Evvie', 'Janu', 'ejanu2k@nasa.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (94, 'Ilyse', 'Yann', 'iyann2l@ibm.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (95, 'Elysha', 'Kimmins', 'ekimmins2m@loc.gov', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (96, 'Isak', 'Blackborn', 'iblackborn2n@youtu.be', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (97, 'Cynthie', 'Stanistrete', 'cstanistrete2o@nydailynews.com', 'STAFF', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (98, 'Mychal', 'Snel', 'msnel2p@craigslist.org', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (99, 'Misti', 'Peron', 'mperon2q@vinaora.com', 'CUSTOMER', NULL);
insert into Customer (id, first_name, last_name, email, role, billing_id) values (100, 'Alford', 'Guppy', 'aguppy2r@desdev.cn', 'ADMIN', NULL);


insert into billing_details (id, account_number, tariff, customer_id) values (101, '1595279784', 9159.51, 1);
insert into billing_details (id, account_number, tariff, customer_id) values (102, '6778251409', 4638.15, 2);
insert into billing_details (id, account_number, tariff, customer_id) values (103, '2156690065', 5858.83, 3);
insert into billing_details (id, account_number, tariff, customer_id) values (104, '9045613794', 1586.01, 4);
insert into billing_details (id, account_number, tariff, customer_id) values (105, '2583425161', 3818.42, 5);
insert into billing_details (id, account_number, tariff, customer_id) values (106, '5301095765', 8813.41, 6);
insert into billing_details (id, account_number, tariff, customer_id) values (107, '1085689743', 5233.66, 7);
insert into billing_details (id, account_number, tariff, customer_id) values (108, '7327861327', 2497.85, 8);
insert into billing_details (id, account_number, tariff, customer_id) values (109, '1077693346', 5673.46, 9);
insert into billing_details (id, account_number, tariff, customer_id) values (110, '2645556043', 4576.44, 10);
insert into billing_details (id, account_number, tariff, customer_id) values (111, '9969995278', 2845.57, 11);
insert into billing_details (id, account_number, tariff, customer_id) values (112, '5655541343', 4012.39, 12);
insert into billing_details (id, account_number, tariff, customer_id) values (113, '4816550526', 4730.45, 13);
insert into billing_details (id, account_number, tariff, customer_id) values (114, '9497449933', 1421.1, 14);
insert into billing_details (id, account_number, tariff, customer_id) values (115, '2396377914', 4947.07, 15);
insert into billing_details (id, account_number, tariff, customer_id) values (116, '0669227803', 5270.04, 16);
insert into billing_details (id, account_number, tariff, customer_id) values (117, '4804992596', 1631.32, 17);
insert into billing_details (id, account_number, tariff, customer_id) values (118, '9448132859', 9834.22, 18);
insert into billing_details (id, account_number, tariff, customer_id) values (119, '4166279033', 5062.15, 19);
insert into billing_details (id, account_number, tariff, customer_id) values (120, '1071376934', 1004.45, 20);
insert into billing_details (id, account_number, tariff, customer_id) values (121, '7535319254', 8790.81, 21);
insert into billing_details (id, account_number, tariff, customer_id) values (122, '6426189294', 4921.52, 22);
insert into billing_details (id, account_number, tariff, customer_id) values (123, '4547134316', 5567.51, 23);
insert into billing_details (id, account_number, tariff, customer_id) values (124, '7787556943', 8080.83, 24);
insert into billing_details (id, account_number, tariff, customer_id) values (125, '2355685428', 9729.2, 25);
insert into billing_details (id, account_number, tariff, customer_id) values (126, '8653781064', 7748.51, 26);
insert into billing_details (id, account_number, tariff, customer_id) values (127, '8794462801', 2883.58, 27);
insert into billing_details (id, account_number, tariff, customer_id) values (128, '2664309005', 8342.15, 28);
insert into billing_details (id, account_number, tariff, customer_id) values (129, '5308688966', 7342.35, 29);
insert into billing_details (id, account_number, tariff, customer_id) values (130, '4189044709', 4638.94, 30);
insert into billing_details (id, account_number, tariff, customer_id) values (131, '5648484518', 8275.08, 31);
insert into billing_details (id, account_number, tariff, customer_id) values (132, '6625180076', 4530.29, 32);
insert into billing_details (id, account_number, tariff, customer_id) values (133, '6768918915', 3302.79, 33);
insert into billing_details (id, account_number, tariff, customer_id) values (134, '1932229590', 3235.88, 34);
insert into billing_details (id, account_number, tariff, customer_id) values (135, '4724145811', 1580.46, 35);
insert into billing_details (id, account_number, tariff, customer_id) values (136, '1264304773', 5908.9, 36);
insert into billing_details (id, account_number, tariff, customer_id) values (137, '8781758081', 3303.13, 37);
insert into billing_details (id, account_number, tariff, customer_id) values (138, '3199551335', 6340.62, 38);
insert into billing_details (id, account_number, tariff, customer_id) values (139, '1455790737', 6227.33, 39);
insert into billing_details (id, account_number, tariff, customer_id) values (140, '3341894683', 8934.74, 40);
insert into billing_details (id, account_number, tariff, customer_id) values (141, '1423767934', 8095.88, 41);
insert into billing_details (id, account_number, tariff, customer_id) values (142, '2409838758', 8925.49, 42);
insert into billing_details (id, account_number, tariff, customer_id) values (143, '7952982877', 4964.98, 43);
insert into billing_details (id, account_number, tariff, customer_id) values (144, '7603860105', 9650.24, 44);
insert into billing_details (id, account_number, tariff, customer_id) values (145, '5828679694', 2710.43, 45);
insert into billing_details (id, account_number, tariff, customer_id) values (146, '6524233344', 4513.47, 46);
insert into billing_details (id, account_number, tariff, customer_id) values (147, '9002205813', 7993.01, 47);
insert into billing_details (id, account_number, tariff, customer_id) values (148, '8534835837', 1080.98, 48);
insert into billing_details (id, account_number, tariff, customer_id) values (149, '2815789841', 7055.06, 49);
insert into billing_details (id, account_number, tariff, customer_id) values (150, '0048294071', 2079.2, 50);
insert into billing_details (id, account_number, tariff, customer_id) values (151, '7846516833', 6149.26, 51);
insert into billing_details (id, account_number, tariff, customer_id) values (152, '9567353433', 9198.51, 52);
insert into billing_details (id, account_number, tariff, customer_id) values (153, '6871063013', 8141.03, 53);
insert into billing_details (id, account_number, tariff, customer_id) values (154, '5753614159', 4226.54, 54);
insert into billing_details (id, account_number, tariff, customer_id) values (155, '2611584788', 6714.87, 55);
insert into billing_details (id, account_number, tariff, customer_id) values (156, '7716501186', 3308.66, 56);
insert into billing_details (id, account_number, tariff, customer_id) values (157, '8534240302', 5717.18, 57);
insert into billing_details (id, account_number, tariff, customer_id) values (158, '6647637818', 6727.13, 58);
insert into billing_details (id, account_number, tariff, customer_id) values (159, '1740125932', 1715.29, 59);
insert into billing_details (id, account_number, tariff, customer_id) values (160, '9332187959', 3202.11, 60);
insert into billing_details (id, account_number, tariff, customer_id) values (161, '2891765583', 5399.06, 61);
insert into billing_details (id, account_number, tariff, customer_id) values (162, '0578181789', 3536.27, 62);
insert into billing_details (id, account_number, tariff, customer_id) values (163, '4486441303', 7664.62, 63);
insert into billing_details (id, account_number, tariff, customer_id) values (164, '9184830999', 4145.29, 64);
insert into billing_details (id, account_number, tariff, customer_id) values (165, '0410491632', 4800.7, 65);
insert into billing_details (id, account_number, tariff, customer_id) values (166, '6826872498', 5200.3, 66);
insert into billing_details (id, account_number, tariff, customer_id) values (167, '5862362525', 5044.0, 67);
insert into billing_details (id, account_number, tariff, customer_id) values (168, '7611424505', 8493.23, 68);
insert into billing_details (id, account_number, tariff, customer_id) values (169, '5339757374', 2628.69, 69);
insert into billing_details (id, account_number, tariff, customer_id) values (170, '7241002393', 2612.58, 70);
insert into billing_details (id, account_number, tariff, customer_id) values (171, '2821444370', 5948.0, 71);
insert into billing_details (id, account_number, tariff, customer_id) values (172, '0950562009', 9652.44, 72);
insert into billing_details (id, account_number, tariff, customer_id) values (173, '0150872739', 9712.68, 73);
insert into billing_details (id, account_number, tariff, customer_id) values (174, '0634436953', 7625.03, 74);
insert into billing_details (id, account_number, tariff, customer_id) values (175, '7494477403', 6019.12, 75);
insert into billing_details (id, account_number, tariff, customer_id) values (176, '3874970884', 7330.81, 76);
insert into billing_details (id, account_number, tariff, customer_id) values (177, '3305718889', 1069.98, 77);
insert into billing_details (id, account_number, tariff, customer_id) values (178, '7591387049', 3249.43, 78);
insert into billing_details (id, account_number, tariff, customer_id) values (179, '2651682047', 3230.25, 79);
insert into billing_details (id, account_number, tariff, customer_id) values (180, '3871756784', 9545.6, 80);
insert into billing_details (id, account_number, tariff, customer_id) values (181, '1844936538', 8164.14, 81);
insert into billing_details (id, account_number, tariff, customer_id) values (182, '8798310844', 8727.41, 82);
insert into billing_details (id, account_number, tariff, customer_id) values (183, '5012269721', 9143.21, 83);
insert into billing_details (id, account_number, tariff, customer_id) values (184, '9821586406', 9064.44, 84);
insert into billing_details (id, account_number, tariff, customer_id) values (185, '9461976909', 1388.94, 85);
insert into billing_details (id, account_number, tariff, customer_id) values (186, '8281941731', 3892.29, 86);
insert into billing_details (id, account_number, tariff, customer_id) values (187, '4648427165', 7912.36, 87);
insert into billing_details (id, account_number, tariff, customer_id) values (188, '4057110224', 2885.83, 88);
insert into billing_details (id, account_number, tariff, customer_id) values (189, '9116446151', 4367.78, 89);
insert into billing_details (id, account_number, tariff, customer_id) values (190, '4412781003', 1408.86, 90);
insert into billing_details (id, account_number, tariff, customer_id) values (191, '8199926295', 9169.66, 91);
insert into billing_details (id, account_number, tariff, customer_id) values (192, '9232408392', 1583.48, 92);
insert into billing_details (id, account_number, tariff, customer_id) values (193, '8134201067', 3063.08, 93);
insert into billing_details (id, account_number, tariff, customer_id) values (194, '3500252486', 4978.72, 94);
insert into billing_details (id, account_number, tariff, customer_id) values (195, '1233944924', 2758.34, 95);
insert into billing_details (id, account_number, tariff, customer_id) values (196, '8037329542', 3937.01, 96);
insert into billing_details (id, account_number, tariff, customer_id) values (197, '0738923451', 5599.85, 97);
insert into billing_details (id, account_number, tariff, customer_id) values (198, '2567528962', 4818.24, 98);
insert into billing_details (id, account_number, tariff, customer_id) values (199, '1876471921', 7086.38, 99);
insert into billing_details (id, account_number, tariff, customer_id) values (200, '9828247844', 6076.21, 100);